--Creazione tabella CORSO
CREATE TABLE CORSO(
	CodiceCorso INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nome VARCHAR(15) NOT NULL,
	Descrizione VARCHAR(50),
	MaxPartecipanti INT NOT NULL,
--	NumLezioni INT,
	DataInizio DATE,
	DataCreazione TIMESTAMP DEFAULT(CURRENT TIMESTAMP()),
	CreatoDa INT,
	DataUltimaModifica TIMESTAMP DEFAULT(CURRENT TIMESTAMP()),
	UltimaModificaDa INT,
);

--Creazione tabella AREA_TEMATICA
CREATE TABLE AREA_TEMATICA(
	CodiceCategoria INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Categoria VARCHAR(16) NOT NULL,
	DataCreazione TIMESTAMP DEFAULT(CURRENT TIMESTAMP()),
	CreatoDa INT,
	DataUltimaModifica TIMESTAMP DEFAULT(CURRENT TIMESTAMP()),
	UltimaModificaDa INT,
);

--Creazione tabella TEMATICA_CORSO
CREATE TABLE TEMATICA_CORSO(
	Categoria VARCHAR(16) NOT NULL,
	CodiceCorso CHAR(10) NOT NULL,
	FOREIGN KEY(CodiceCorso) REFERENCES CORSO(CodiceCorso),
	FOREIGN KEY(Categoria) REFERENCES AREA_TEMATICA(Categoria),	
);

--Creazione tabella RESPONSABILE
CREATE TABLE RESPONSABILE(
	CodiceResponsabile INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nome VARCHAR(15) NOT NULL,
	Cognome VARCHAR(15) NOT NULL,
	LuogoNascita VARCHAR(15),
	DataNascita DATE,
	CodiceFiscale CHAR(16) NOT NULL,
	Username VARCHAR(16),
	Pwd VARCHAR(16),
);

--Creazione tabella STUDENTE
CREATE TABLE STUDENTE(
	Matricola CHAR(10) PRIMARY KEY,
	Nome VARCHAR(15) NOT NULL,
	Cognome VARCHAR(15) NOT NULL,
	LuogoNascita VARCHAR(15),
	DataNascita DATE,
	CodiceFiscale CHAR(16) NOT NULL,
);

--Creazione tabella DOCENTE
CREATE TABLE DOCENTE(
	CodiceDocente INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nome VARCHAR(15) NOT NULL,
	Cognome VARCHAR(15) NOT NULL,
	LuogoNascita VARCHAR(15),
	DataNascita DATE,
	CodiceFiscale CHAR(16) NOT NULL,
);

--Creazione tabella LEZIONE
CREATE TABLE LEZIONE (
	CodiceLezione INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Titolo VARCHAR(16),
	Descrizione VARCHAR(32),
	Durata INTERVAL,
	DataOraInizio TIMESTAMP,
	CodiceCorso INT NOT NULL,
	CodiceDocente INT NOT NULL,
	FOREIGN KEY(CodiceCorso) REFERENCES CORSO(CodiceCorso),
	FOREIGN KEY(CodiceDocente) REFERENCES DOCENTE(CodiceDocente),
);

--Creazione tabella PARTECIPARE
CREATE TABLE PARTECIPARE(
	Matricola CHAR(10) NOT NULL,
	CodiceLezione INT NOT NULL,
	FOREIGN KEY(Matricola) REFERENCES STUDENTE(Matricola),
	FOREIGN KEY(CodiceLezione) REFERENCES LEZIONE(CodiceLezione),
);

--Creazione tabella ISCRIZIONE
CREATE TABLE ISCRIZIONE(
	CodiceCorso INT,
	Matricola CHAR(10),
	FOREIGN KEY(CodiceCorso) REFERENCES CORSO(CodiceCorso),
	FOREIGN KEY(Matricola) REFERENCES STUDENTE(Matricola)
);

